CREATE TABLE IF NOT EXISTS app_user (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN','DEVELOPER','TESTER','SYSTEM_ANALYST','TEAM_LEAD'))
    );